
image: Ubuntu 

stack: jdk 11  

branches:
  only:
    - master 

build: off 

install:
 

  - java -jar ./artrifacts/app-order.jar &

build_script:
  - ./gradlew test -Dselenide.headless=true
  - ./gradlew test --info  
